# Рабочая тетрадь 2
## Данные в машинном обучении



### Библиотека NumPy

NumPy (NumericalPython) - это библиотека Python с открытым исходным кодом, которая используется практически во всех областях науки и техники. Это универсальный стандарт для работы с числовыми данными в Python.

Чтобы начать использовать NumPy необходимо импортировать соответствующую библиотеку:
```
import numpy as np
```
Основным объектом NumPy является однородный многомерный массив (в numpy называется numpy.ndarray). Это многомерный массив элементов (обычно чисел), одного типа.
```
Наиболее важные атрибуты объектов ndarray:
    ndarray.ndim - число измерений (чаще их называют "оси") массива.
    ndarray.shape - размеры массива, его форма. Это кортеж натуральных
чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
    ndarray.size - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape.
    ndarray.dtype - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. NumPy здесь предоставляет целый букет возможностей, как встроенных, например: bool_, character, int8, int16, int32,  nt64, float8, float16, float32, float64, complex64, object_, так и возможность определить собственные типы данных, в том числе и составные.
    ndarray.itemsize - размер каждого элемента массива в байтах.
    ndarray.data - буфер, содержащий фактические элементы массива.
Обычно не нужно использовать этот атрибут, так как обращаться к
элементам массива проще всего с помощью индексов.
```

### Пример 1
Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.

In [2]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


### Пример 2
```
 Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.
```

In [4]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10,20)
print(a, '\n', b, '\n', c, '\n', d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


### Пример 3
Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.


In [5]:
Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.037935533139432764 0.9953492607318654 0.5177884468590631


### Пример 4
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.


In [7]:
A = np.arange(25).reshape(5,5)
A[[0,1]]=A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Пример 5
```
Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [11]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


### Пример 6
Отсортировать массив.


In [12]:
arr = np.array([2,1,5,3,7,4,6,8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


### Залание 1
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [34]:
a = np.full([8,8],[[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0]])
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Задание 2

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.


In [7]:
import numpy as np
A = np.full([5,5],np.arange(5))
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### Задание 3
Создать массив 3x3x3 со случайными значениями.

In [11]:
import numpy as np
A = np.random.random((3,3,3))
print(A)

[[[0.9930718  0.03105339 0.74050182]
  [0.99413126 0.2158155  0.95501016]
  [0.37081405 0.20841404 0.4916109 ]]

 [[0.39770836 0.98070436 0.581773  ]
  [0.06644592 0.23153849 0.57498501]
  [0.80485808 0.9557563  0.58333601]]

 [[0.07696001 0.38695864 0.96877225]
  [0.78505576 0.22504158 0.52001132]
  [0.10971375 0.56622775 0.27517788]]]


### Задание 4
Создать матрицу с 0 внутри, и 1 на границах.

In [18]:
import numpy as np
print("Введите длину и ширину матрицы: ")
a,b = map(int, input().split())
C = np.full([a,b], 0)
for i in range(a):
    for j in range(b): 
        if (i == 0 or i == a-1 or j == 0 or j == b -1):
            C[i][j] = 1
print(C)

Введите длину и ширину массива: 
5 5
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Задание 5
Создайте массив и отсортируйте его по убыванию.

In [24]:
import numpy as np
print("Введите длинну массива: ")
a = int(input())
b = np.random.randint(1, 10, a)
print(np.sort(b)[::-1])

Введите длинну массива: 
5
[9 8 7 3 2]


### Задание 6
Создайте матрицу, выведите ее форму, размер и размерность.

In [30]:
import numpy as np
import random
a = random.randint(1,20)
b = random.randint(1,20)
C = np.random.randint(20,100,[a,b])
print(C)
if a == b:
    print("Форма матрицы - квадрат")
else:
    print("Форма матрицы - прямоугольник")
print("Размер матрицы:", a, "X",b)
print("Размерность матрицы: ", a*b)

[[99 69 57]
 [66 89 67]
 [71 79 94]
 [99 28 27]
 [84 99 72]
 [21 83 78]
 [79 82 98]]
Форма матрицы - прямоугольник
Размер матрицы: 7 X 3
Размерность матрицы:  21


## Библиотека Pandas
```
    Первым шагом в любом начинании в области машинного обучения является введение исходных данных в систему. Исходные данные могут вводиться вручную, содержаться в файле или храниться в интернете в каком-либо формате. Кроме того, часто требуется получить данные из нескольких источников.
    Библиотека pandas – это удобный и быстрый инструмент для работы с данными, обладающий большим функционалом. Если очень кратко, то pandas – это библиотека, которая предоставляет очень удобные с точки зрения использования инструменты для хранения данных и работе с ними.
    Библиотека pandas предоставляет две ключевые структуры данных: Series и DataFrame.
    Series – это одномерная структура данных, ее можно представить, как таблицу с одной строкой. С Series можно работать как с обычным массивом (обращаться по номеру индекса), и как с ассоциированным массивом, когда можно использовать ключ для доступа к элементам данных.
    DataFrame – это двумерная структура. Идейно она очень похожа на 
обычную таблицу, что выражается в способе ее создания и работе с ее 
элементами.
```

### Пример 1
Создать Series из списка Python, словаря Python, и массва Numpy (установить буквенные метки для последнего)

In [3]:
import pandas as pd
import numpy as np
lst = [1,2,3,4,5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1,2,3,4,5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a','b','c','d','e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


### Пример 2
Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме)

In [4]:
import pandas as pd

s1 = pd.Series([1,2,3,4,5],['a','b','c','d','e'])
s2 = pd.Series([5,4,3,2,1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


### Пример 3
Создайте новый фрейм данных

In [5]:
import pandas as pd
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон','Стивен Стивенсон']
dataframe['Возраст'] = [38,25]
dataframe['Водитель'] = [True,False]
print(dataframe)

                Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False


### Пример 4
Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv

In [61]:
import pandas as pd
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe= pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

### Пример 5
Пронализировать характеристики фрейма данных.

In [50]:
import pandas as pd
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe= pd.read_csv(url)
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

### Пример 6
Выберите индивидуальные данные или срезы фрейма данных

In [8]:
import pandas as pd
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe= pd.read_csv(url)
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

### Пример 7
Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров
первого класса.

In [9]:
import pandas as pd
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe= pd.read_csv(url)
dataframe[dataframe['PClass']=='1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

### Задание 1
Найти евклидово расстояние между двумя Series (точками) a и b, неиспользуя встроенную формулу.

In [14]:
import pandas as pd
import numpy as np
print("Введите координаты первой точки")
a,b,c = map(int, input().split())
A = np.array([a,b,c])
print("Введите координаты второй точки")
d,e,f = map(int, input().split())
B = np.array([d,e,f])
s1 = pd.Series(A)
s2 = pd.Series(B)
op1 = np.sqrt(np.sum(np.square(s1-s2)))
print(op1)

Введите координаты первой точки
1 3 3
Введите координаты второй точки
8 8 8
9.9498743710662


### Задание 2
Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных

In [20]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/abolone.csv'
dataframe= pd.read_csv(url)
dataframe.head(10)

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   
5      I   0.425     0.300   0.095        0.3515          0.1410   
6      F   0.530     0.415   0.150        0.7775          0.2370   
7      F   0.545     0.425   0.125        0.7680          0.2940   
8      M   0.475     0.370   0.125        0.5095          0.2165   
9      F   0.550     0.440   0.150        0.8945          0.3145   

   Viscera weight  Shell weight  Rings  
0          0.1010         0.150     15  
1          0.0485         0.070      7  
2          0.1415         0.210      9  
3          0.1140         0.155     10  
4          0.0395         0.055      7  
5          0.0775         0.120      8  
6          0.1415         0.330     20  
7          0.1495         0.260     16  
8          0.1125         0.165      9  
9          0.1510         0.320     19

### Задание 3
Проделать с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 5-7

In [65]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/abolone.csv'
dataframe = pd.read_csv(url)
#dataframe.head(3)
#dataframe.tail(5)
#dataframe.shape
#dataframe.describe()
##url1 = 'https://raw.githubusercontent.com/akmand/datasets/main/abolone.csv'
#dataframe1 = pd.read_csv(url1)
#dataframe.iloc[1:4]
dataframe[dataframe['Shell weight']==0.150].head(10)

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
0        M   0.455     0.365   0.095        0.5140          0.2245   
47       F   0.460     0.375   0.120        0.4605          0.1775   
53       F   0.470     0.360   0.120        0.4775          0.2105   
193      I   0.355     0.275   0.085        0.2200          0.0920   
282      F   0.455     0.355   0.120        0.4495          0.1770   
298      M   0.490     0.395   0.140        0.5490          0.2215   
304      F   0.470     0.360   0.130        0.4720          0.1820   
406      M   0.450     0.355   0.115        0.4790          0.2125   
588      M   0.450     0.335   0.140        0.4625          0.1640   
947      M   0.475     0.370   0.125        0.5370          0.2220   

     Viscera weight  Shell weight  Rings  
0            0.1010          0.15     15  
47           0.1100          0.15      7  
53           0.1055          0.15     10  
193          0.0600          0.15      8  
282          0.1040          0.15      9  
298          0.1275          0.15     11  
304          0.1140          0.15     10  
406          0.1045          0.15      8  
588          0.0760          0.15     14  
947          0.1215          0.15      9

## Работа с числовыми данными
Количественные данные что-то измеряют – будь то размер класса, ежемесячные продажи или оценки учащихся. Естественным способом представления этих величин является численным (например, 150 студентов, $529 392 продаж). 

***Нормализация данных*** — это общепринятая задача предобработки в машинном обучении. Многие алгоритмы предполагают, что все признаки находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1. 
   
Существует множество способов нормализации значений признаков, чтобы масштабировать их к единому диапазону и использовать в различных моделях машинного обучения. В зависимости от используемой функции, их можно разделить на 2 большие группы: линейные и нелинейные. При нелинейной нормализации в расчетных соотношениях используются функции логистической сигмоиды или гиперболического тангенса. В
линейной нормализации изменение переменных осуществляется пропорционально, по линейному закону.

На практике наиболее распространены следующие методы нормализации признаков:

***Минимакс*** – линейное преобразование данных в диапазоне [0..1], где
минимальное и максимальное масштабируемые значения
соответствуют 0 и 1 соответственно;

***Z-масштабирование*** данных на основе среднего значения и
стандартного отклонения: производят деление разницы между
переменной и средним значением на стандартное отклонение.

При масштабировании данных мы будем использовать одну из
популярных библиотек машинного обучения Scikit-learn. Библиотека
содержит пакет sklearn.preprocessing, который предоставляет широкие
возможности для нормализации данных. Следует отметить, что в целом
алгоритмы обучения выигрывают от стандартизации набора данных.

### Пример 1
Прошкалируйте числовой признак в диапазон между двумя значениями.

In [39]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

### Пример 2
Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное отклонение 1.

In [41]:
import numpy as np
from sklearn import preprocessing

x = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
standardized

array([[-1.26687088],
       [-0.39316683],
       [-0.17474081],
       [ 0.0436852 ],
       [ 1.79109332]])

### Пример 3
Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
Необходимо масштабировать его числовые столбцы

In [42]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big','small','big','small','small']})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

### Задача
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [74]:
import pandas as pd
from sklearn import preprocessing
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe= pd.read_csv(url)
scaler = preprocessing.MinMaxScaler()
dataframe[['sepal_length_cm']] = scaler.fit_transform(dataframe[['sepal_length_cm']])
sclr = preprocessing.StandardScaler()
dataframe[['sepal_width_cm']] = scaler.fit_transform(dataframe[['sepal_width_cm']])
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        0.625000              1.4             0.2   
1           0.166667        0.416667              1.4             0.2   
2           0.111111        0.500000              1.3             0.2   
3           0.083333        0.458333              1.5             0.2   
4           0.194444        0.666667              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667        0.416667              5.2             2.3   
146         0.555556        0.208333              5.0             1.9   
147         0.611111        0.416667              5.2             2.0   
148         0.527778        0.583333              5.4             2.3   
149         0.444444        0.416667              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]